# -*- coding: utf-8 -*-
"""dpo_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvTxAY0w6txvwxx9jiWEwM8jcTWp3WfP
"""
# !pip install bitsandbytes
# !pip install trl
# !pip install -U bitsandbytes

import torch
from transformers import AutoTokenizer

"""# Get base model"""

device = torch.device('cuda' if torch.cuda.is_available() else ('mps' if torch.backends.mps.is_available() else 'cpu'))
print(device)

model_name = 'google/gemma-2b-it'
tokenizer = AutoTokenizer.from_pretrained(model_name)
print(tokenizer.chat_template)

messages = [
{"role": "user", "content": 'this is the prompt'},
{"role": "assistant", "content": 'this is the completion'},
{"role": "user", "content": 'this is the prompt2'},
{"role": "assistant", "content": 'this is the completion2'},
]

t = tokenizer.apply_chat_template(messages, tokenize=False)
print(t)